spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/contract_db}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/contract_db}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: techandrewwilliam@gmail.com
    password: kxrd hizk yfry meiy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


docusign:
  private-key: ${DOCUSIGN_PRIVATE_KEY}
  integration-key: ${DOCUSIGN_INTEGRATION_KEY}
  user-id: ${DOCUSIGN_USER_ID}
  account-id: ${DOCUSIGN_ACCOUNT_ID}
  auth-server: ${DOCUSIGN_AUTH_SERVER}





google:
  credentials:
    token-store-path: /app/tokens
    path: credentials.json
  oauth:
    redirectUri: https://contract-image-latest.onrender.com/api/v1/googleOauth/google-callback
  calendar:
    user-id: williamekene700@gmail.com

jwt:
  key: ${JWT_KEY}

server:
  port: 5050


AWS:
  REGION: eu-north-1
  ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}


