spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://postgres:5432/contract_db
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
   mongodb:
     uri: mongodb://localhost:27017/contract_db
